### ISSUE TITLE
Static files not found django 1.9

### ISSUE THREAD

**Issue by frmdstryr** [hendrix/hendrix#116]
I keep getting static files not found.  

https://hendrix.readthedocs.org/en/latest/static_files/ is empty.

Works fine using `python manage.py runserver`

I added `STATIC_ROOT` and `HENDRIX_CHILD_RESOURCES` to `settings.py` as shown in the example.

Using python 2.7.10 on windows  and django 1.9.2.

Any suggestions?

Thanks!

**Comment by vepkenez** [comment]
so in your django settings you have something like:
`HENDRIX_CHILD_RESOURCES = (
    'hendrix.contrib.resources.static.DjangoStaticsFinder'
)`

and you are running `hx start`?

**Comment by vepkenez** [comment]
and by "the example" do you mean this:
https://github.com/hendrix/hendrix/blob/master/examples/django_hx_chatserver/example_app/example_app/settings.py#L90-L98

**Comment by frmdstryr** [comment]
Yes, yes.

I believe it's because I'm trying to run using HendrixDeploy and not the hx command.

**Comment by vepkenez** [comment]
Right.  The examples were made and work using `hx start` which automates some of the needed configuration of django's settings.  I am certain it will work if you launch that way.

I am not sure if anyone has consolidated and/or documented the steps that are needed for HendrixDeploy to do everything needed for django to work completely with statics and other settings dependent features.

**Comment by frmdstryr** [comment]
Ok, well using `hx start` is working fine, so closing.
