### ISSUE TITLE
logger is not defined in resources.py

### ISSUE THREAD

**Issue by frmdstryr** [hendrix/hendrix#117]
Undefined variable 'logger' in https://github.com/hendrix/hendrix/blob/d28117fc02c06b16b8b8f22ff3507015264deac7/hendrix/facilities/resources.py#L91

**Comment by jMyles** [comment]
This is a bug.  @billjohnston noticed it just a few days ago.  We'll release a bugfix release for this pronto.  Thanks for the report!

Hope you are well.

**Comment by jMyles** [comment]
I'm surprised and slightly taken aback to find that there isn't a test that covers this.  @frmdstryr, do you have one, or do you care to write one?  I'm happy to help you do this if it will help.

**Comment by frmdstryr** [comment]
No, don't have a test... From looking at the warning I'm guessing it just comes because I have one app overriding css & js in another.

**Comment by jMyles** [comment]
Do you think you can produce a test which causes this error to occur?  The
patch is obvious and easy, so I'm happy to slap it on once we have a test.

On Mon, Feb 8, 2016 at 3:06 PM, frmdstryr <notifications@github.com> wrote:

> No, don't have a test... From looking at the warning I'm guessing it just
> comes because I have one app overriding css & js in another.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hendrix/hendrix/issues/117#issuecomment-181507983>.
>



-- 
Justin Myles Holmes
http://github.com/jMyles/

**Comment by frmdstryr** [comment]
Cheers

**Comment by frmdstryr** [comment]
FYI. This still fails (at least on windows). It should be `self.logger.warn` not `self.logger.warning`.

**Comment by jMyles** [comment]
You are absolutely right.  My bad.

On Thu, Feb 11, 2016 at 9:48 AM, frmdstryr <notifications@github.com> wrote:

> FYI. This still fails (at least on windows). It should be self.logger.warn
> not self.logger.warning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hendrix/hendrix/issues/117#issuecomment-182894788>.
>



-- 
Justin Myles Holmes
http://github.com/jMyles/
