### ISSUE TITLE
Forbidden resource 

### ISSUE THREAD

**Issue by bahaa96** [hendrix/hendrix#118]
This my first project with hendrix I've applied this tut :
[hendrix demo: Django, async, websockets, and telnet w/ Twisted & hendrix. Django-NYC @ Buzzfeed
](https://www.youtube.com/watch?v=92VeMkjM1TQ)

and my project is a copy of the one in the video. But i got this issue.
![capture11](https://cloud.githubusercontent.com/assets/8254655/12805205/313cfa38-cb02-11e5-992e-292d74ada1d4.PNG)

**Comment by jMyles** [comment]
Interesting. Nothing immediately stands out to me.  @anthonyalmarza, @vepkenez ?

**Comment by jMyles** [comment]
@bahaa96: Is your entry module (ie, run.py) available for inspection?

**Comment by bahaa96** [comment]
Yeah bro but could u make a simple another tutorial about a simple example as i think the problem is in my urls.py file to as u didn't put any thing in it in the tutorial except the index view :+1:

**Comment by bahaa96** [comment]
Your Tutorial which recorded from the conference is good but the text resolution isn't good maybe i missed something but i was guessing, please make another one.

**Comment by vepkenez** [comment]
@bahaa96 I am not sure what you've got going on so far but if you use the "django_hx_chatserver" example [here](https://github.com/hendrix/hendrix/tree/master/examples), that should work and maybe put some of the pieces together for you.

**Comment by bahaa96** [comment]
ok bro i'll try

**Comment by jMyles** [comment]
@bahaa96, the code, in the state that it was when this video ended, is available here:

https://github.com/jMyles/hendrix-demo-django-nyc

**Comment by bahaa96** [comment]
Ok bro it works now, u can close this issue now :rotating_light:

**Comment by jMyles** [comment]
@bahaa96: Awesome!  What made it work for you?

**Comment by bahaa96** [comment]
@jMyles I dunno it the same code but yours works but mine shows this error but my ur github code here https://github.com/jMyles/hendrix-demo-django-nyc is unlike mine and the one in the video in the first parameter of putChild it's "hendrix-demo" in the video and "messages in the code on github is it matters .
![capture1](https://cloud.githubusercontent.com/assets/8254655/12865920/571b5d80-ccc4-11e5-94f2-0ad5a3e67068.PNG)

**Comment by bahaa96** [comment]
@jMyles Ive followed u on twitter bro. Very interested in this project :+1:
