### ISSUE TITLE
Reload issues on windows

### ISSUE THREAD

**Issue by frmdstryr** [hendrix/hendrix#125]
On Windows (have not tried linux), I noticed that if my django app has an import error that causes the import of the WSGI app to fail, it goes into an infinite reload loop without printing out the error.  I'm not sure why it's triggering a FileModifiedEvent (as the file is NOT changing), but watchdog is calling `on_any_event` causing a reload to occur which kills the previous server process before the error is outputted.  

Adding a 1 sec sleep in https://github.com/hendrix/hendrix/blob/ece7d9b7d7fcc76d826d310eee043fad7360f5ee/hendrix/ux.py#L58 before killing the process fixes this.

Also, if django fails to start (due to database connection error, or invalid user credentials) the same thing is happening (but it's not fixed by the above change).  Didn't have a chance to dig through as to why yet. Any suggestions?

**Comment by bahaa96** [comment]
Where's ur code man ?

**Comment by frmdstryr** [comment]
Just add "raise ImportError()" to wsgi.py in  a new project

**Comment by jMyles** [comment]
@frmdstryr: what happened?  why closed?

**Comment by frmdstryr** [comment]
Seems like some setup issue with the system (can't reproduce on another)

**Comment by frmdstryr** [comment]
Update, this may be related to: https://github.com/hendrix/hendrix/blob/bc8b13d0e50f58cbab5a0cc27d9a48d51aa6a6c4/hendrix/options.py#L25

Should the return statement be indented there?
