### ISSUE TITLE
It's working Synchronically on Pythonanywhere 

### ISSUE THREAD

**Issue by bahaa96** [hendrix/hendrix#131]
How to make run.py my default running file on any hosting

**Comment by jMyles** [comment]
Hey @bahaa96.  How are you?  I haven't tried on Pythonanywhere.  What's the config?

**Comment by bahaa96** [comment]
I dunno what the meaning of the config it's the first time to publish a website, which hosting service have u tried?

**Comment by bahaa96** [comment]
Bro how u can help me, is it works on heroku ?

**Comment by jMyles** [comment]
Unfortunately, I really don't know how to proceed.  Perhaps you can ask
Docker people and post some of their assessments back here on this ticket?
Maybe that will give us a better idea.
