### ISSUE TITLE
Twisted==16.6.0 with zope.interface==4.3.2

### ISSUE THREAD

**Issue by bliedblad** [hendrix/hendrix#134]
First... great project! 
I've been using Twisted for years and Hendrix helped me add a web based front end to my project. 

Now to the issue...
I just had a case where I installed a new library to my project using "pip install -U new_library". This updated Twisted from 16.2.0  and Zope from 4.2.0. 

Seems like this causes 'hxmessages' to not percolate back to the browser.

At this point, not sure if it was Twisted or Zope which caused the issue, but I was able to roll-back to the older versions of Twisted and Zope, so this isn't an emergency.

Might be worth looking at for the next build.

**Comment by jMyles** [comment]
Hey, nice to meet you.  :-)  So hmm - interesting.  It's not immediately clear to me what might be causing this problem.

Is there any other light you can shed at this time from your development environment?  Specifically:

* Does updating only one but not the other cause the problem?  Or do both need to be updated to those versions?
* If you are using a SockJSResource, does that Resource still properly get instantiated and put on the proper child path?  Only to then malfunction later during run time?  Or does it 404?  Or some other thing?

**Comment by bliedblad** [comment]
Hi Justin,

Updated zope.interface, tested -> works.
With updated Zope in place, made update to Twisted -> Fails.
With both updated, rolled back Zope... Still not working.

So, must be some interaction with the Twisted update.

I am using **sockjs-0.3.4.min.js** in conjunction with javascript to enable/disable buttons and update displayed text based on what the application is doing behind the scenes. Used your examples and the YouTube lecture to get this far, so I don't think I'm doing anything crazy... Unless using Hendrix is crazy ;-) .

The template loads fine... Chrome's developer tools shows sockjs is in the html and in the 'Network' tab, I can see that the websocket is loaded 

No 404s, no errors, but javascript which would normally enable/disable buttons isn't called. Not sure if sock.onmessage() didn't get hooked, or if messages are not getting posted... that's a bit too far under the hood for my current level of understanding.

**Comment by jMyles** [comment]
Yeah, good work man.

Is the project that exemplifies this bug currently open source?  If so, can you link it from this ticket?  If not, can you put together a super short example?

**Comment by bliedblad** [comment]
Not open source, for a customer of mine... Probably have time to try to reproduce using the examples included in the Hendrix source tree though, give me a day or two.

**Comment by jMyles** [comment]
Understood.  So, for the mean time, in order to meet the customer's needs, you are going to use a prior release of Twisted?

I'm definitely interested in getting this figured out; helping people deliver quality products to their clients (and make bank doing it) is obviously a priority.  :-)

**Comment by bliedblad** [comment]
Yeah, will just use previous release of Twisted.
 
Unless the new library I need to use won't work with the older Twisted, no reason the older version shouldn't work. 

Still need to test the new library, just wanted to log the issue before moving on to a work-around.

**Comment by bliedblad** [comment]
Hi Justin,

Ok... Pretty easy to duplicate. Here are the steps I took this morning.
1) Clone hendrix repository
2) Change directory to /hendrix/examples/django_hx_chatserver
3) Run install script (install.sh) -> application fails to run as "--traceback" option cannot be found.
4) Run using "hx start --dev" -> I received error when accessing from another PC.
5) Add IP address of "server" to 'ALLOWED_HOSTS'
6) Run again using "hx start --dev"
7) Test with two browser windows.... **NOT WORKING**
8) Check installed library versions using 'pip freeze' -> yup, Twisted==16.6.0
9) Rollback Twisted, "pip install Twisted==16.2.0"
10) Test with two browser windows... **WORKING**

Hope this helps. Not sure why I had to add my IP to 'ALLOWED_HOSTS', don't have this on my application and it works (more than likely something I fixed 5-6 months ago, so don't worry about it).

**Comment by gmaclinuxer** [comment]
it works for me to update requrirements to:
Django==1.8.11
Twisted==16.1.1
#Twisted==16.0.0 WORKING TOO
watchdog==0.8.3
zope.interface==4.0.5
txsockjs==1.2.2
cffi==1.9.1
hendrix==2.0.2
invocations==0.12.0
service-identity==16.0.0

**Comment by bliedblad** [comment]
For hendrix 2.0.2, rollback dependencies and it will work.
