### ISSUE TITLE
Is it workable now?

### ISSUE THREAD

**Issue by kamranhossain** [hendrix/hendrix#137]
Is it workable or not? I see that the last commit was almost two years ago.

**Comment by jMyles** [comment]
It's in a rough state at the moment, but I do want to shine it back into fashion.

**Comment by bliedblad** [comment]
I've been using version 2.0.2 since it's release.

Still awesome.

**Comment by kamranhossain** [comment]
Thanks for the reply.
I see this is an awesome project.
@jMyles  are you working on an update new version?
Which version of Django and Twisted do you work with? @bliedblad

**Comment by bliedblad** [comment]
Hi Kamran,

The one time I tried to install requirements without specific versions
defined, Twisted intsalled latest and I had an error with it and Zope (see
issues).

Rolling back Twisted/zope combination solved the problem.
Django== 1.9.7
Twisted==16.2.0
zope.interface==4.2.0
hendrix==2.0.2

Have not tried to update anything in over a year...there are probably
vulnerabilities which have been patched, but my use case does not require
the project to be on the internet, just local "trusted" networks...
And... if it isn't broken, don't fix it?

**Comment by jMyles** [comment]
My current vision for it includes:
* Full(er) compatibility with Python 3
* Working with Django 2.0 / ASGI
* Working with the latest cryptography.io to do TLS termination inside the application.

Does that interest y'all?  Anybody want to help me haul it across those lines?

**Comment by bliedblad** [comment]
Hi Justin,

I work with robotics and I had an existing Python 2.7 project which used
Twisted for TCP/IP socket communication and multithreaded capability (i.e.
callFromThread, callLater, LoopingCall).

A few years back, I needed a way to expose my program to the local network
(or web), plus be able to store some data in a database (single file based
sqllite is sufficient, not a lot of data).

I experimented with Django and found that it worked well for what I needed
on database/web interface, but wasn't able to merge everything until I
found a way to run Django AND Twisted.

That's were hendrix came in.

Yes, it would be nice to get Chrome to stop warning me that my connection
is not secure...
I'm too busy to help this year, but probably have some time early next
year.

I could for sure help with regression testing on my current app to see if
updating hendrix causes any issues with a Python 2.7 app.
Not sure I'm ready to migrate to Python 3 yet though - it might be too much
work to migrate.

**Comment by kamranhossain** [comment]
Sound interesting. I am not a super programmer. But let me know if somehow I contribute to this workflow. Will you want to include Django-channels or use WebSocket as you work previously?
ASGI is an interesting project and I come across another one uvicorn from @tomchristie. It contains uvloop and httptools. A minimal application interface, based on ASGI. @jMyles 
 @bliedblad, nice to hear from you. Your workflow suited with Hendrix.

**Comment by vepkenez** [comment]
@kamranhossain fwiw I know of a couple of production websites that are and have been using hendrix for a few years reliably and without any issues.

http://pro.reelio.com
http://darknet.jp

**Comment by jMyles** [comment]
Everybody in this thread: do try the latest version (3.0.0).  We'll have another major release (4.0.0) coming soon to support Python 3.7.
