### ISSUE TITLE
django_hx_chatserver out of date, message_signal.connect equivalent with version 3+?

### ISSUE THREAD

**Issue by bliedblad** [hendrix/hendrix#156]
My use case for using hendrix 2 is very similar to how django_hx_chatserver works.
I have web sockets sending data in both directions.

I am in the process of converting over to Python3 and hendrix 3.1. 
First (bonehead) mistake on my part was not realizing that hey_joe has a different signature than hxdispatcher.send(). Switched the parameter order and it works like magic!

The other direction is another story... but having a hell of a time figuring that out.

I can step into hendrix and see how hx_subscribe is processed (this is a message from the client's websocket), but can't seem to figure out how other messages from are/should be routed to my message handler. 

What is the equivalent of using "from hendrix.contrib.concurrency.signals import message_signal" with "message_signal.connect(fn)"?

**Comment by jMyles** [comment]
Hola @bliedblad - I'm not 100% sure.  Maybe we're supposed to be emitting that message from `hey_joe` and we aren't?  This might be a genuine bug.

**Comment by bliedblad** [comment]
@jMyles - I don't understand most of how hendrix works under the hood, so in my mind, you are truly a wizard!

I'm going to have a hard time figuring this one out on my own, but thinking it might have something to do with the removal of "MessageResource.putChild" in contrib/async/resources.py

Thoughts?
