### ISSUE TITLE
c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory

### ISSUE THREAD

**Issue by collinanderson** [hendrix/hendrix#43]
just ran pip install hendrix and got an error.

{{{
c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
}}}

`distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

**Comment by sunyoubo** [comment]
I also install libffi-dev, but useless, I'm install scarpy on ubuntu 10.04.4

**Comment by zirou30** [comment]
Thank you very matt @cancan101 Solved my problem.

**Comment by antime** [comment]
I also deal with it by "sudo apt-get install libffi-dev"

**Comment by WandyLau** [comment]
# sudo apt-get install libffi-dev 
it works for me in Ubuntu 16.04
