### ISSUE TITLE
Unspecified Dependencies 

### ISSUE THREAD

**Issue by KPrasch** [hendrix/hendrix#60]
There are a number of dependencies not in REQUIREMENTS, and several linux packages that also need to be listed in the README. Here are some of them:

**Python**
pyOpenSSL
cryptography

**Linux**
libffi-dev
libssl-dev

**Comment by JamesTFarrington** [comment]
I've submitted a pull request, that adds the python dependencies to requirements.txt, and the linux dependencies to the README. This seems to have caused the Travis CI build to fail. This needs to be some kind of build related issue instead.

**Comment by jMyles** [comment]
I... actually think this is resolved.  The SSL reqs are listed as an option in setup.py, and the ubuntu requirements are outlined in the quickstart on the first page of the docs:

http://hendrix.readthedocs.org/en/2.0.0/

Thus, I'm marking this closed.
