### ISSUE TITLE
hx can raise a bad error if there's an ImportError raised by the app's wsgi module.

### ISSUE THREAD

**Issue by jMyles** [hendrix/hendrix#99]
So, imagine you are trying to import the wsgi module, but your wsgi.py file has an ImportError.  You end up getting this message:

https://github.com/hendrix/hendrix/blob/559fa7f2b1ed96f225dbe74b21144bee6d634499/hendrix/ux.py#L158

**Comment by JamesTFarrington** [comment]
I'd like to do something about this one as well.

https://github.com/hendrix/hendrix/blob/559fa7f2b1ed96f225dbe74b21144bee6d634499/hendrix/ux.py#L233
